# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cancan-rest-links}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-09-17}
  s.description = %q{Guard your links with permissions}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/cancan-rest-links.rb",
     "lib/cancan-rest-links/helpers/rest_links.rb",
     "lib/cancan-rest-links/namespaces.rb",
     "lib/cancan-rest-links/rails/configure.rb",
     "spec/cancan-rest-links/link_helpers_spec.rb",
     "spec/cancan-rest-links/rails/configure_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cancan-rest-links}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rest link helpers for CanCan}
  s.test_files = [
    "spec/cancan-rest-links/link_helpers_spec.rb",
     "spec/cancan-rest-links/rails/configure_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0"])
      s.add_runtime_dependency(%q<cancan>, ["~> 1.3"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1.1"])
      s.add_runtime_dependency(%q<sugar-high>, ["~> 0.1"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.0.0"])
      s.add_dependency(%q<cancan>, ["~> 1.3"])
      s.add_dependency(%q<require_all>, ["~> 1.1"])
      s.add_dependency(%q<sugar-high>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.0.0"])
    s.add_dependency(%q<cancan>, ["~> 1.3"])
    s.add_dependency(%q<require_all>, ["~> 1.1"])
    s.add_dependency(%q<sugar-high>, ["~> 0.1"])
  end
end

