require 'require_all'
require 'sugar-high/module'
require 'sugar-high/alias'
require 'cancan-rest-links/namespaces'
require_all File.dirname(__FILE__) + '/cancan-rest-links/helpers'
require_all File.dirname(__FILE__) + '/cancan-rest-links/rails'
